### ISSUE TITLE
Unable to use a number as an enum selector

### ISSUE THREAD

**Issue by wordaddict** [terra-kelz/ngx-dynamic-form#1]
I was unable to use a number as an enum selector, when i try rendering it , it doesn't render at all and also gives white spaces.

**Comment by terra-kelz** [comment]
Hi wordaddict, thanks for dropping by, please can you create this issue in this repository https://github.com/Terragon-Engineering/ngx-dynamic-form. in the meantime your issue is being attended too.

**Comment by terra-kelz** [comment]
This issue has been resolved in version 0.0.45674-development.
